export const LOAD_USERS_START="LOAD_USERS_START"

export const CREATE_USER_START="CREATE_USER_START"

export const DELETE_USER_START="DELETE_USER_START"

export const UPDATE_USER_START="UPDATE_USER_START"

export const SEARCH_USER_START="SEARCH_USER_START"

export const FILTER_USER_START="FILTER_USER_START"

export const SORT_USER_START="SORT_USER_START"